User.create!([
  {full_name: "sam wells", email: "sam2@test.com", password_digest: "$2a$12$4JOPxeQYq8LQ/Mw0Do3P/uFZNZtdXHjBp5Erfot9/0xKvPWprfzAe", user_image_url: "https://media.licdn.com/dms/image/C4E03AQEVsg4p5PSgKA/profile-displayphoto-shrink_800_800/0/1547178604396?e=2147483647&v=beta&t=Qrq9uDeN9olxnu5ucU0ESYTLzNCzganyO-VeY7I_PdI"}
])
Painting.create!([
  {name: "Starry Starry Night", artist_id: 1, description: "'Starry Starry Night' is a renowned painting by Vincent Van Gogh featuring a swirling night sky filled with vibrant stars, a small village with darkened buildings, and a prominent cypress tree in the foreground. The painting captures the artist's emotional and imaginative interpretation of the nocturnal landscape.", year: 1889, price: "629.0", painting_image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/800px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg"},
  { name: "Low Tide", artist_id: 2, description: "'Low Tide' is a painting by Joaquin Sorolla depicting a coastal scene with figures, capturing the tranquility of a beach at low tide, with soft, luminous brushstrokes and a harmonious color palette.", year: 1903, price: "513.0", painting_image: "https://i.pinimg.com/originals/4b/f7/ce/4bf7ceff1b2db7eb5ea168d3b407366d.jpg" },
  { name: "San Giorgio Maggiore at Dusk", artist_id: 3, description: "'San Giorgio Maggiore at Dusk' is a painting by Claude Monet depicting the island of San Giorgio Maggiore in Venice during twilight. The artwork captures the ethereal atmosphere of the fading light, with a focus on the play of colors and the reflection of the island's architecture on the water.", year: 1908, price: "598.0", painting_image: "https://upload.wikimedia.org/wikipedia/commons/d/da/Claude_Monet%2C_Saint-Georges_majeur_au_cr%C3%A9puscule.jpg" },
  { name: "A Sunday Afternoon On The Island Of La Grande Jatte", artist_id: 5, description: "'A Sunday Afternoon on the Island of La Grande Jatte' is a masterpiece of Pointillism and depicts a serene scene along the Seine River, showcasing meticulously placed dots of paint to create a harmonious composition of people leisurely strolling and enjoying their day in the park.", year: 1885, price: "721.0", painting_image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/A_Sunday_on_La_Grande_Jatte%2C_Georges_Seurat%2C_1884.jpg/1200px-A_Sunday_on_La_Grande_Jatte%2C_Georges_Seurat%2C_1884.jpg" },
  { name: "Swans Reflecting Elephants", artist_id: 4, description: "'Swans Reflecting Elephants' is a surrealist painting by Salvador Dali that depicts three swans floating on a calm lake, with their reflections forming the shapes of elephants. The artwork explores the concept of transformation and illusion, blending the boundaries between reality and imagination.", year: 1937, price: "734.0", painting_image: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f6/Swans_reflecting_elephants.jpg/350px-Swans_reflecting_elephants.jpg" },
  { name: "The Persistence of Memory", artist_id: 4, description: "'The Persistence of Memory' by Salvador Dali, painted in 1931, is a surreal masterpiece featuring melting clocks in a dreamlike landscape, challenging our perception of time and reality. The painting's imagery evokes a sense of temporal distortion and invites contemplation on the fluidity of existence.", year: 1931, price: "529.0", painting_image: "https://upload.wikimedia.org/wikipedia/en/d/dd/The_Persistence_of_Memory.jpg" },
  { name: "The Tilled Field", artist_id: 6, description: "'The Tilled Field' is a surrealist painting by Joan Miro characterized by bold, abstract forms and vibrant colors, depicting a whimsical landscape with various organic and geometric shapes.", year: 1923, price: "739.0", painting_image: "https://upload.wikimedia.org/wikipedia/en/thumb/9/9d/The_Tilled_Field.jpg/1200px-The_Tilled_Field.jpg" },
  { name: "The Son of Man", artist_id: 7, description: "'The Son of Man' is a surrealist painting by René Magritte featuring a man in a dark suit and bowler hat, with a green apple obscuring his face, creating a mysterious and thought-provoking image.", year: 1964, price: "856.0", painting_image: "https://upload.wikimedia.org/wikipedia/en/thumb/e/e5/Magritte_TheSonOfMan.jpg/350px-Magritte_TheSonOfMan.jpg" },
  { name: "Nighthawks", artist_id: 8, description: "'Nighthawks' is a iconic painting by Edward Hopper depicting a late-night diner scene in which four individuals, illuminated by the bright interior lights, are isolated and contemplative, evoking a sense of urban loneliness and alienation.", year: 1942, price: "751.0", painting_image: "https://upload.wikimedia.org/wikipedia/commons/a/a8/Nighthawks_by_Edward_Hopper_1942.jpg" },
  { name: "Christina's World", artist_id: 9, description: "'Christina's World' is a renowned painting by Andrew Wyeth depicting a young woman, Christina Olson, lying in a field and looking towards a distant farmhouse, capturing a sense of isolation and longing.", year: 1948, price: "763.0", painting_image: "https://upload.wikimedia.org/wikipedia/en/thumb/a/a2/Christinasworld.jpg/500px-Christinasworld.jpg" },
  { name: "The Stone Breakers", artist_id: 10, description: "'The Stone Breakers' is a painting by Gustave Courbet that depicts two laborers engaged in the arduous task of breaking stones. It portrays the harshness and toil of the working class, highlighting the social inequalities prevalent during the time it was painted.", year: 1849, price: "815.0", painting_image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Gustave_Courbet_-_The_Stonebreakers_-_WGA05457.jpg/1200px-Gustave_Courbet_-_The_Stonebreakers_-_WGA05457.jpg" },
  { name: "The Horse Fair", artist_id: 11, description: "'The Horse Fair' is a monumental painting depicting a bustling scene of horse traders and their horses in Paris, capturing the energy and movement of the animals as well as the lively atmosphere of the fair.", year: 1854, price: "810.0", painting_image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Rosa_Bonheur%2C_The_Horse_Fair%2C_1852%E2%80%9355.jpg/450px-Rosa_Bonheur%2C_The_Horse_Fair%2C_1852%E2%80%9355.jpg" },
  { name: "Villa Borghese", artist_id: 12, description: "'Villa Borghese' is an abstract expressionist painting by Willem de Kooning, characterized by vibrant colors, bold brushstrokes, and a dynamic composition. It features a gestural and energetic style, reflecting de Kooning's exploration of the human form and his unique approach to abstraction.", year: 1960, price: "925.0", painting_image: "https://www.sartle.com/media/artwork/villa-borghese-willem-de-kooning.jpg" },
  { name: "Harmony Squares with Concentric Rings", artist_id: 13, description: "'Harmony Squares with Concentric Rings' is an abstract painting by Wassily Kandinsky characterized by vibrant geometric forms and bold colors, showcasing his pioneering exploration of non-representational art.", year: 1913, price: "805.0", painting_image: "https://i.pinimg.com/564x/67/bc/a2/67bca2388ff50f6443fdbe0898fee500.jpg" },
  { name: "Suprematist Composition", artist_id: 14, description: "'Suprematist Composition' by Kazimir Malevich is an abstract painting characterized by geometric shapes and a limited color palette. It features a black square positioned diagonally on a white background, emphasizing the artist's exploration of pure form and non-objective art.", year: 1916, price: "725.0", painting_image: "https://upload.wikimedia.org/wikipedia/commons/1/13/Suprematist_Composition_-_Kazimir_Malevich.jpg" },
  { name: "Black Square", artist_id: 14, description: "'Black Square' is a groundbreaking painting by Kazimir Malevich, completed in 1915. With its stark black square set against a white background, it symbolizes the complete rejection of representational art and embraces the concept of pure form and non-objectivity, challenging the very essence of traditional artistic expression.", year: 1915, price: "840.0", painting_image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Kazimir_Malevich%2C_1915%2C_Black_Suprematic_Square%2C_oil_on_linen_canvas%2C_79.5_x_79.5_cm%2C_Tretyakov_Gallery%2C_Moscow.jpg/1200px-Kazimir_Malevich%2C_1915%2C_Black_Suprematic_Square%2C_oil_on_linen_canvas%2C_79.5_x_79.5_cm%2C_Tretyakov_Gallery%2C_Moscow.jpg" },

])
Category.create!([
  {name: "Realism"},
  {name: "Impressionism"},
  {name: "Surrealism"},
  {name: "Abstract"}
])
Artist.create!([
  {name: "Vincent Van Gogh", birthplace: "Zundert, Netherlands", fun_fact: "Despite his remarkable talent and impact on the art world, Vincent van Gogh only sold one painting during his lifetime. However, his posthumous recognition soared, cementing his status as one of the most celebrated and influential artists in history.", date_of_birth: "March 30, 1853"},
  {name: "Joaquin Sorolla", birthplace: "Valencia, Spain", fun_fact: "Joaquin Sorolla was known as the 'master of light' due to his remarkable ability to capture the effects of sunlight in his paintings. His unique style and skillful use of color earned him international recognition during his lifetime.", date_of_birth: "February 27, 1863"},
  {name: "Claude Monet", birthplace: "Paris, France", fun_fact: "Monet's painting 'Impression, Sunrise' gave the name to the entire Impressionist movement. The term, 'Impressionism' was derived from a critic's comment on the painting, in which he used the word 'impression' to describe Monet's style.", date_of_birth: "November 14, 1840"},
  {name: "Salvador Dali", birthplace: "Figueres, Spain", fun_fact: "Salvador Dali once arrived at a party in a Rolls-Royce filled with cauliflower, explaining that he wanted to make a grand entrance with a car full of vegetative growth.", date_of_birth: "May 11, 1904"},
  {name: "Georges Seurat", birthplace: "Paris, France", fun_fact: "A fun fact about Seurat is that his most famous painting, 'A Sunday on La Grande Jatte,' took him two years to complete, and he used over three million individual dots to create the masterpiece.", date_of_birth: "December 2, 1859"},
  {name: "Joan Miro", birthplace: "Barcelona, Spain", fun_fact: "Joan Miró was known for his unconventional artistic style, and he often used unusual materials in his works, such as burnt objects, rope, and even shoes. He believed that art should be free from traditional constraints, allowing for spontaneous and imaginative expression.", date_of_birth: "April 20, 1893"},
  {name: "René Magritte", birthplace: "Lessines, Belgium", fun_fact: "One of René Magritte's most famous artworks is 'The Son of Man,' featuring a bowler-hatted man with an apple obscuring his face. This image has become an iconic symbol, representing the juxtaposition of hidden truths and the mysteries of the human condition in Magritte's art.", date_of_birth: "November 21, 1898"},
  {name: "Edward Hopper", birthplace: "Nyack, New York", fun_fact: "Edward Hopper's iconic painting, 'Nighthawks' was initially met with mixed reviews, but has since become one of the most recognizable works of American art, inspiring countless parodies, homages, and references in popular culture.", date_of_birth: "July 22, 1882"},
  {name: "Andrew Wyeth", birthplace: "Chadds Ford, Pennsylvania", fun_fact: "One of Andrew Wyeth's most famous paintings is 'Christina's World,' which depicts a woman crawling through a field. The inspiration for the painting was Wyeth's neighbor, Christina Olson, who had a degenerative muscular disorder and could only crawl due to her condition.", date_of_birth: "July 12, 1917"},
  {name: "Gustave Courbet", birthplace: "Ornans, France", fun_fact: "Gustave Courbet was known for his strong political convictions and involvement in social causes. He actively participated in the Paris Commune of 1871, a radical socialist and revolutionary government that briefly ruled Paris. As a result, he was briefly imprisoned and had to pay fines for his political activities.", date_of_birth: "June 10, 1819"},
  {name: "Rosa Bonheur", birthplace: "Bordeaux, France", fun_fact: "Despite living in a time when women were not commonly accepted as professional artists, Rosa Bonheur became one of the most renowned animal painters of the 19th century, and her fame led her to receive numerous awards and honors, including being the first woman to receive the French Legion of Honor.", date_of_birth: "March 16, 1822"},
  {name: "Willem de Kooning", birthplace: "Rotterdam, Netherlands", fun_fact: "Willem de Kooning, a prominent Dutch-American abstract expressionist artist, was known for his unique approach to painting. Despite being left-handed, he would often paint with both hands simultaneously, creating energetic and dynamic brushstrokes on his canvases.", date_of_birth: "April 24, 1904"},
  {name: "Wassily Kandinsky", birthplace: "Moscow, Russia", fun_fact: "Kandinsky had synesthesia, a neurological condition that caused him to perceive colors and shapes as sounds, and he often referred to his paintings as 'compositions' in reference to the musical elements he incorporated into his artwork.", date_of_birth: "December 16, 1866"},
  {name: "Kazimir Malevich", birthplace: "Kiev, Ukraine", fun_fact: "Malevich's most famous painting, 'Black Square,' was initially exhibited in 1915 and consisted of a simple black square on a white background, challenging traditional notions of representational art.", date_of_birth: "February 23, 1879"}
])
